### PR TITLE
Update to v1.14.1

### LINKED ISSUE #3: Update to sinon 1.12.2

### PR DESCRIPTION
**Pull request by ryneeverett**
Close #3.

### CODE REVIEW

**Comment by rbabayoff** [comment]
Give me a couple of days

**Comment by rbabayoff** [comment]
Sorry for the delay. Published as v1.14.1_1

**Comment by ryneeverett** [comment]
sweet! Autopublish would have been nice, but it still looks pretty daunting at this point. Actually I'm not sure if it would even be possible given the manual namespacing we do here.

**Comment by rbabayoff** [comment]
I would have loved autopublish, but both here and in chai, the default scripts just don't work out of the box.

**Pull request merged**
