### PR TITLE
run sinon package on debug mode only.

### PR DESCRIPTION
**Pull request by pahans**

### CODE REVIEW

**Comment by ryneeverett** [comment]
Unfortunately I don't think this is possible unless we want to access sinon through `Package['practicalmeteor:sinon']`, because `debugOnly` disables `api.export`. See meteor issues [#3116](https://github.com/meteor/meteor/issues/3116) and [#3639](https://github.com/meteor/meteor/issues/3639).

**Comment by ryneeverett** [comment]
That said, I think that would be a worthwhile cost to avoid shipping this package to clients.

**Comment by ryneeverett** [comment]
Better yet, we could hack around the limitation [like meteor-mocha-web did](https://github.com/mad-eye/meteor-mocha-web/commit/ae40582dacb0790cc191d672df3e20065497a04b).

**Comment by rbabayoff** [comment]
All of our code is in packages, so sinon get's loaded with us only in package tests. If you use it to test apps using velocity, then this is a velocity + meteor issue. I have no problem to add debugOnly, if it doesn't break our tests, which I believe it does right now.

**Comment by rbabayoff** [comment]
Updated in pr #9

**Pull request closed without merging**
